all options
Mestr3z/burger-react pull request #1
Opened 2022-02-13 22:37 UTC by Mestr3z

2022-02-14 06:37 UTC, ChrisGerBy requested changes
Здравствуйте!

Вы проделали большую работу, написали множество функциональных компонентов, научились использовать хуки useState и useEffect - это хороший результат!

Однако, Вам необходимо внимательнее вчитываться в требования задания курса, чтобы Ваша работа была принята.
Для приемки работы Вам необходимо будет исправить ВСЕ замечания с пометкой Надо исправить, а также подправить верстку.

Подробности указаны в комментариях к коду.
Особое внимание хочу уделить следующим моментам:
- описание propTypes: `any` недопустимо в рамках этого задания. Каждая пропса должна иметь конкретный тип.
- стили должны быть импортированы как модули, а не как css. Изучите, пожалуйста, эту функциональность и примените во всех файлах.
- Вам необходимо изучить, что такое портал в реакте и применить это при написании компоненты Modal;
- должны быть два компонента: и Modal, и ModalOverlay. Каждый из них должен выполнять свою функцию. Поэтому Вам необходимо будет переписать свой код с учетом требования задания.

Также рекомендую Вам воспользоваться возможностями IDE для форматирования кода (добавление/удаление отпустов, удаление лишних разбивочных строк, выстраивание иерархии уровней и тд). Это сделает Ваш код чище, аккуратнее, читабельнее.


Замечания по верстке:
- не выровнен контент (хедер и основной контент);
- в модалке order-details иконка галочки должна быть крупнее и иметь фон;
**Ваша разметка:**
![image](https://user-images.githubusercontent.com/45519864/153804109-c6cc0c8a-3617-4634-9288-3401d7f2942f.png)
___
<img width="617" alt="image" src="https://user-images.githubusercontent.com/45519864/153807475-9dd0b417-5cbb-4be2-929d-7b096e53cd96.png">


**Макет:**
<img width="835" alt="image" src="https://user-images.githubusercontent.com/45519864/153804082-164ef644-ddba-43a3-ae2b-1ee594196487.png">
___
<img width="540" alt="image" src="https://user-images.githubusercontent.com/45519864/153807461-60ae236f-0976-4121-9f03-8e3050c7b8fb.png">


Желаю Вам успехов!

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
> +import image from "../../../node_modules/@ya.praktikum/react-developer-burger-ui-components/dist/images/img.png";
**Надо исправить**
Вы получили изображение булки с бэкэнда так же, как и изображения соусов и начинок. Поэтому импорт картинки из библиотеки таким образом необходимо удалить и поставить актуальную картинку на булку.

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
> +              <img className="" src={card.image_mobile}></img>
**Надо исправить**
неверное использование JSX.
Если нет дочерних элементов в img (а тэг img не подразумевает дочерних элементов), то тэг должен быть самозакрывающимся:
```
              <img className="" src={card.image_mobile} />

```
<img width="961" alt="image" src="https://user-images.githubusercontent.com/45519864/153809292-4822f268-2bf1-4674-b817-815644defe14.png">


https://ru.reactjs.org/docs/jsx-in-depth.html

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
> +          <img className="burger__constructor_bun" src={image}></img>
**Надо исправить**
неверное использование JSX.
Если нет дочерних элементов в img (а тэг img не подразумевает дочерних элементов), то тэг должен быть самозакрывающимся:
```
              <img className="" src={card.image_mobile} />

```
<img width="961" alt="image" src="https://user-images.githubusercontent.com/45519864/153809292-4822f268-2bf1-4674-b817-815644defe14.png">


https://ru.reactjs.org/docs/jsx-in-depth.html

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/ingredient-details/ingredient-details.tsx
> +import { createAdd } from "typescript";
**Надо исправить**
неиспользуемые импорт. Необходимо удалить его либо использовать.

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/ingredient-details/ingredient-details.tsx
> +import { CheckMarkIcon } from "@ya.praktikum/react-developer-burger-ui-components";
**Надо исправить**
неиспользуемые импорт. Необходимо удалить его либо использовать.

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/ingredient-details/ingredient-details.tsx
> +      <h2 className = 'ingridients-details__title mt-15 ml-10 text_type_main-large'>Детали ингредиента</h2>
**Можно лучше**
подправьте, пожалуйста, написание слова `ingredients` во всем этом файле (буква **e** в середине слова вместо **i**).

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/app-header/app-header.tsx
> +import "../../../node_modules/@ya.praktikum/react-developer-burger-ui-components/dist/ui/common.css";
**Надо исправить**
если библиотека подключена согласно инструкции в документации, то импортировать отдельные стили в каждом компоненте, где эта библиотека используется нет необходимости. 
Проверьте, пожалуйста, еще раз документацию библиотеки и уберите прямые импорты из node_modules  ВО ВСЕХ ФАЙЛАХ. 
Вы должны импортировать только необходимый компонент/иконку.

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/app-header/app-header.tsx
> +import "../../../node_modules/@ya.praktikum/react-developer-burger-ui-components/dist/ui/box.css";
**Надо исправить**
если библиотека подключена согласно инструкции в документации, то импортировать отдельные стили в каждом компоненте, где эта библиотека используется нет необходимости. 
Проверьте, пожалуйста, еще раз документацию библиотеки и уберите прямые импорты из node_modules  ВО ВСЕХ ФАЙЛАХ. 
Вы должны импортировать только необходимый компонент/иконку.

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
> +import "../../../node_modules/@ya.praktikum/react-developer-burger-ui-components/dist/ui/box.css";
**Надо исправить**
если библиотека подключена согласно инструкции в документации, то импортировать отдельные стили в каждом компоненте, где эта библиотека используется нет необходимости. 
Проверьте, пожалуйста, еще раз документацию библиотеки и уберите прямые импорты из node_modules  ВО ВСЕХ ФАЙЛАХ. 
Вы должны импортировать только необходимый компонент/иконку.

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/burger-ingredients/burger-ingredients.tsx
> +import "../../../node_modules/@ya.praktikum/react-developer-burger-ui-components/dist/ui/box.css";
**Надо исправить**
если библиотека подключена согласно инструкции в документации, то импортировать отдельные стили в каждом компоненте, где эта библиотека используется нет необходимости. 
Проверьте, пожалуйста, еще раз документацию библиотеки и уберите прямые импорты из node_modules  ВО ВСЕХ ФАЙЛАХ. 
Вы должны импортировать только необходимый компонент/иконку.

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/burger-ingredients/burger-ingredients.tsx
> +import { CurrencyIcon } from "@ya.praktikum/react-developer-burger-ui-components";
**Можно лучше**
```
import { CurrencyIcon, Tab } from "@ya.praktikum/react-developer-burger-ui-components";
```

из одного модуля можно импортировать таким образом.

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/app/App.tsx
> +  })
**Надо исправить**
согласно заданию,
```
логика навешивания и удаления обработчиков события нажатия клавиши "Esc" описана в компоненте Modal;
```

Если модалка не открыта, то нам не нужно слушать нажатие клавиши Escape. Поэтому эта логика должна быть внутри компоненты Modal, а не компоненты App.

2022-02-14 06:37 UTC, ChrisGerBy commented on src/components/ingredient-details/ingredient-details.tsx
> +    <ModalOverlay onClose = {props.onClose} isOpen = {props.isOpen}>
**Надо исправить**
согласно заданию,
```
в компоненте Modal используется портал;
```

Изучите, пожалуйста, что такое портал, как используется и примените эти знания для написания компоненты Modal: https://ru.reactjs.org/docs/portals.html

2022-02-20 11:13 UTC, ChrisGerBy requested changes
Здравствуйте! 
Вы исправили большую часть замечаний. 
Однако, осталось ещё несколько важных нюансов к исправлению. Подробнее - в комментариях к коду.

Успехов в исправлении!

2022-02-20 11:13 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +
**Можно лучше**
Отформатируйте, пожалуйста, код. Уберите лишние пустые строки и сделайте уровневость (перед вложенными тегами должно быть больше отступов, чем перед родителями).

2022-02-20 11:13 UTC, ChrisGerBy commented on src/components/order-details/order-details.module.css
> +    margin: 0;
**Надо исправить**
Отступы должны быть заданы с помощью возможностей библиотеки, а не в css стилях, согласно заданию.

2022-02-25 12:27 UTC, ChrisGerBy requested changes
Здравствуйте!
Для принятия задания и перехода к следующему этапу обучения необходимо исправить ВСЕ пункты **Надо исправить**.

Обратите, пожалуйста, внимание, что с предыдущей итерации не исправлен комментарий: https://github.com/Mestr3z/burger-react/pull/1#discussion_r805534110

Также не совсем точно реализовано требование и propTypes для массивов и обьектов. Обратитесь, пожалуйста, к документации propTypes и изучите все возможности описать пропсы. В коде не должно остаться PropTypes.object.

Рекомендую также пройтись по коду форматтером (например, https://prettier.io/).

Желаю успехов!

2022-02-25 12:27 UTC, ChrisGerBy commented on src/components/app/App.tsx
> +          setBurgerCounstructorPrices(burgerCounstructorPrices + card.price);
**Надо исправить**
Неоптимальное решение. Для каждого ингредиента Вы меняете Стейт цены. Вынесите эту логику в конец, когда все ингредиенты уже разложены, что посчитать цену всего один раз.
Можете воспользоваться методом reduce массива.

2022-03-14 08:25 UTC, ChrisGerBy requested changes
Здравствуйте!
Для принятия задания и перехода к следующему этапу обучения необходимо исправить ВСЕ пункты **Надо исправить**.

Обратите, пожалуйста, внимание, что с предыдущей итерации не исправлен комментарий: https://github.com/Mestr3z/burger-react/pull/1#discussion_r805534110

Итоговая стоимость бургера на данный момент отображается неверная. Согласно заданию, стоимость должна высчитываться, исходя из добавленных ингредиентов. Эту логику расчета итоговой стоимость Вам необходимо исправить.

Вы прописали точный propType. Отличная работа! Таким образом было исправлено замечание из предыдущей итерации. Однако, можно сделать еще лучше, вынеся повторяющийся propType в отдельную переменную и переиспользовать ее везде, где в пропсах приходит ингредиент.

Рекомендую Вам внимательно пройтись по ВСЕМ оставшимся комментариям и исправить код, согласно замечаниям, не добавляя новых ошибок. Вы уже близки к завершению этого этапа!

Желаю успехов!

2022-03-14 08:25 UTC, ChrisGerBy commented on src/utils/Api.tsx
> +    console.log(err.code, err.message);
**Надо исправить**
Проверьте, пожалуйста, эту функциональность еще раз. То, что Вы увидите в консоли, будет `undefined undefined`. 
Изучите, пожалуйста, внимательно, как работает Promise.reject (к слову, Вы верно разобрались с методом промиса, но не до конца изучили, что же придется в error в блоке catch).

2022-03-14 08:25 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.module.css
> +}
**Можно лучше**
добавьте, пожалуйста, пустую строку в конце файла, чтобы избавиться от "кирпича" гитхаба.

2022-03-14 08:25 UTC, ChrisGerBy commented on src/components/app/App.tsx
> +          setBurgerCounstructorPrices(burgerCounstructorPrices + card.price);
**Надо исправить**
выше (строка 80) у Вас уже рассчитана стоимость и положена в стейт. Однако, в 86 и 95 строке Вы кладете новые значения в стейт. 
В конечном итоге у Вас неверно рассчитанная стоимость показывается в приложении. Вам нужно исправить функциональность так, чтобы итоговая стоимость под добавленными ингредиентами всегда была верная (какие ингредиенты добавлены, такая стоимость и отображается).

<img width="428" alt="image" src="https://user-images.githubusercontent.com/45519864/158130800-25efb174-904a-43a6-a079-afcd2fb6d317.png">

2022-03-14 08:25 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
> +    __v: PropTypes.number,
**Надо исправить**
ниже Вы трижда копи-пастите один и тот же propType. Следует придерживаться принципа  DRY - don't repeat yourself - и выносить повторяющиеся фрагменты кода в отдельную переменную и переиспользовать ее.
Опять же: если вдруг изменится сам объект ингредиента (добавятся новые поля и изменятся/удалятся существующие), Вам придется по всему коду исправлять это. А в идеале, конечно, исправить в одном месте.
Поэтому рекомендую создать, например, в папке utils некоторый файл, в котором Вы будете хранить подобного рода propTypes.

2022-03-14 08:25 UTC, ChrisGerBy commented on src/components/modal/modal.tsx
> +function modal(props: any) {
**Надо исправить** 
компоненты должны называться с большой буквы:
https://ru.reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized

2022-03-21 08:30 UTC, ChrisGerBy requested changes
Здравствуйте!

Пожалуйста, не игнорируйте неисправленные **Надо исправить** замечания. Если у Вас есть вопросы по реализации, обратитесь за помощью к наставникам.

Из предыдущих итераций:
- https://github.com/Mestr3z/burger-react/pull/1#discussion_r805534110
- https://github.com/Mestr3z/burger-react/pull/1#discussion_r814716254
- https://github.com/Mestr3z/burger-react/pull/1#discussion_r825674411
- https://github.com/Mestr3z/burger-react/pull/1#discussion_r825678584
- https://github.com/Mestr3z/burger-react/pull/1/files#r805524716

При исправлениях на этой итерации Вы допустили ошибку в реализации блока  catch при загрузке ингредиентов. См. комментарий.

Также упустили компонент BurgerConstructor, где следует также импортировать созданный propType для ingredient-item.

Для того чтобы пройти на следующий этап, необходимо исправить ВСЕ замечания с пометкой **Надо исправить**. Пожалуйста, уделите внимание каждому.

Успехов!

2022-03-21 08:30 UTC, ChrisGerBy commented on src/utils/Api.tsx
> +      .catch((err) => {
**Надо исправить**

1. Это неверный синтаксис для блока catch.

```
promise
  .then(callback)
  .catch(callback)
```

Catch не может быть вложен внутрь then. Это отдельный блок.

https://learn.javascript.ru/promise-error-handling

2. Также можно было обратить внимание, что после `Promise.reject(`Error: ${res.status}`)` - код недоступен, то есть  никогда не исполнится.

Рекомендую Вам проверять имплементацию и убедиться, что ошибка запроса обрабатывается верно, есть заход в блок catch и логика работает так, как требует задание.
Для того чтобы зайти в блок можно изменить url на несуществующий, например.

3.  Комментарий к предыдущей имплементации все еще не исправлен.
 https://github.com/Mestr3z/burger-react/pull/1#discussion_r825674411

2022-03-21 08:30 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
> +  data: PropTypes.arrayOf(PropTypes.shape({
**Надо исправить**
следует использовать созданный в src/utils/shared/ingredient-item.js тип.

2022-03-21 08:30 UTC, ChrisGerBy commented on src/components/burger-constructor/burger-constructor.tsx
> +  card: PropTypes.shape({
**Надо исправить**
следует использовать созданный в src/utils/shared/ingredient-item.js тип.

2022-06-06 21:03 UTC, gennady-bars commented on src/components/burger-ingredients/burger-ingredients.tsx
> +            <div className={`${S.burgerElement} ml-4 mr-2 mt-6`} onClick = {() => {props.onCardClick(card)}}>
* При отрисовке массива компонентов нужно всегда указывать уникальный атрибут `key` в самом верхнем уровне верстки.

Для атрибута `key` лучше всего использовать уникальный `id` : у карточки как раз есть такой только с нижним подчеркиванием `_id`
[Почему индекс не нужно использовать, можно прочитать тут:]( https://medium.com/russian/%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%B2-%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5-%D0%BA%D0%BB%D1%8E%D1%87%D0%B0-%D0%B0%D0%BD%D1%82%D0%B8-%D0%BF%D0%B0%D1%82%D1%82%D0%B5%D1%80%D0%BD-56bab8ada309)

2022-06-06 21:04 UTC, gennady-bars commented on src/utils/Api.tsx
> +    .catch((err) => {
Лучше не использовать `catch` в `Api`, так как ловить ошибки нужно в самом конце цепочки запроса, а конец цепочки находится в (`App.js`) после всего  кода, который происходит в `then`. И в реальных проектах в `catch` происходит много логики: открывается попап с ошибкой и тд. Поэтому файл `api` не может знать, что делать с ошибкой внутри.

2022-06-15 17:29 UTC, merged